spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/li4
    username: root
    password: ruca1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true